#!/usr/bin/env python3
"""Xcode build phase: package a CPython 3.13 device runtime and signed modules."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import plistlib
import shutil
import struct
import subprocess


def validate_device_binary(path):
    """Reject ARM64 macOS and simulator binaries even though their CPU matches."""
    data = Path(path).read_bytes()
    if len(data) < 32:
        raise ValueError(f"Not a Mach-O binary: {path}")
    magic, cpu, _, _, count, commands_size, _, _ = struct.unpack_from("<8I", data)
    if magic != 0xFEEDFACF or cpu != 0x0100000C:
        raise ValueError(f"Requires a thin ARM64 iOS device binary: {path}")
    offset = 32
    end = offset + commands_size
    if end > len(data):
        raise ValueError(f"Truncated Mach-O commands: {path}")
    device = False
    for _ in range(count):
        if offset + 8 > end:
            raise ValueError(f"Truncated Mach-O command: {path}")
        command, size = struct.unpack_from("<2I", data, offset)
        if size < 8 or offset + size > end:
            raise ValueError(f"Invalid Mach-O command size: {path}")
        if command == 0x32:  # LC_BUILD_VERSION
            if size < 24:
                raise ValueError(f"Invalid platform command: {path}")
            platform = struct.unpack_from("<I", data, offset + 8)[0]
            if platform != 2:  # PLATFORM_IOS; simulator is 7, macOS is 1.
                raise ValueError(f"Expected iOS device platform, found {platform}: {path}")
            device = True
        elif command == 0x25:  # LC_VERSION_MIN_IPHONEOS, older device builds.
            device = True
        elif command in (0x24, 0x2F, 0x30):
            raise ValueError(f"Not an iOS device binary: {path}")
        offset += size
    if not device:
        raise ValueError(f"Missing iOS device platform metadata: {path}")


def copy_tree(source, destination, *, checkout_root=False):
    source, destination = Path(source).resolve(), Path(destination).resolve()
    if source == destination or source in destination.parents or destination in source.parents:
        raise ValueError(f"Packaging source/destination overlap: {source} and {destination}")
    if destination.exists():
        shutil.rmtree(destination)
    ignore_common = shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store", ".git", ".hg", ".svn")

    def ignore(directory, names):
        excluded = ignore_common(directory, names)
        if checkout_root and Path(directory) == source:
            excluded.update({".venv", "venv", "build", "dist"}.intersection(names))
        return excluded

    shutil.copytree(source, destination, ignore=ignore)


def package_extensions(root, bundle, bundle_id, sign):
    names = set()
    frameworks = bundle / "Frameworks"
    frameworks.mkdir(exist_ok=True)
    for binary in sorted(root.rglob("*.so")):
        validate_device_binary(binary)
        relative = binary.relative_to(root)
        # An extension can use an ABI suffix; package directories remain intact.
        name = ".".join((*relative.parts[:-1], relative.name.split(".")[0]))
        if name in names or (frameworks / f"{name}.framework").exists():
            raise ValueError(f"Duplicate native module framework: {name}")
        names.add(name)
        framework = frameworks / f"{name}.framework"
        framework.mkdir()
        executable = framework / name
        shutil.move(str(binary), executable)
        marker = binary.with_suffix(".fwork")
        marker.write_text(executable.relative_to(bundle).as_posix() + "\n")
        (framework / f"{name}.origin").write_text(marker.relative_to(bundle).as_posix() + "\n")
        (framework / ".melty-extension").touch()
        (framework / "Info.plist").write_bytes(plistlib.dumps({
            "CFBundleExecutable": name, "CFBundleIdentifier": f"{bundle_id}.{name}".replace("_", "-"),
            "CFBundlePackageType": "FMWK", "CFBundleVersion": "1", "CFBundleShortVersionString": "1.0",
            "MinimumOSVersion": "17.0", "CFBundleSupportedPlatforms": ["iPhoneOS"],
        }))
        sign(framework)
    return names


def prepare(config, bundle, *, identity=None, signing_allowed=True):
    bundle = Path(bundle).resolve()
    if bundle.suffix != ".app" or not bundle.is_dir():
        raise ValueError("Packaging requires an existing Xcode .app build directory")
    if signing_allowed and not identity:
        raise ValueError("Device extension signing requires EXPANDED_CODE_SIGN_IDENTITY")
    # Delete only frameworks previously generated by this phase.
    for marker in (bundle / "Frameworks").glob("*.framework/.melty-extension"):
        shutil.rmtree(marker.parent)
    (bundle / "python").mkdir(exist_ok=True)
    copy_tree(Path(config["python_lib"]), bundle / "python/lib")
    copy_tree(Path(config["app_dir"]), bundle / "app", checkout_root=True)
    copy_tree(Path(config["bootstrap_dir"]), bundle / "host")
    packages = bundle / "app_packages"
    if config.get("packages_dir"):
        copy_tree(Path(config["packages_dir"]), packages)
    else:
        if packages.exists():
            shutil.rmtree(packages)
        packages.mkdir()
    (bundle / "HostSettings.plist").write_bytes(plistlib.dumps({"entry_module": config["entry_module"]}))

    def sign(framework):
        if signing_allowed:
            subprocess.run(["/usr/bin/codesign", "--force", "--sign", identity,
                            "--timestamp=none", str(framework)], check=True)

    # Linked dependencies must be embedded frameworks. Do not silently ship a
    # desktop NumPy/Pillow wheel or leave an unsigned vendored dylib in resources.
    for root in (bundle / "python/lib", bundle / "app", packages):
        dylibs = list(root.rglob("*.dylib"))
        if dylibs:
            raise ValueError(f"Convert dependent dylibs to device frameworks before packaging: {dylibs[0]}")
    roots = (bundle / "python/lib/python3.13/lib-dynload", bundle / "app", packages)
    modules = set()
    for root in roots:
        modules.update(package_extensions(root, bundle, config["bundle_id"], sign))
    remaining = list((bundle / "python").rglob("*.so"))
    if remaining:
        raise ValueError(f"Put additional native packages in --packages-dir: {remaining[0]}")
    return modules


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    args = parser.parse_args()
    try:
        config = json.loads(args.config.read_text())
        target = os.environ.get("CODESIGNING_FOLDER_PATH") or os.environ.get("TARGET_BUILD_DIR", "") + "/" + os.environ.get("WRAPPER_NAME", "")
        modules = prepare(config, target, identity=os.environ.get("EXPANDED_CODE_SIGN_IDENTITY"),
                          signing_allowed=os.environ.get("CODE_SIGNING_ALLOWED", "YES") != "NO")
        print(f"Packaged CPython 3.13 and {len(modules)} ARM64 iOS extension frameworks")
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Cannot package iOS Python runtime: {error}\n")


if __name__ == "__main__":
    main()
